Added version sub-command
savannahostrowski/ghost pull request #11
Opened 2023-06-13 16:32 UTC by Galzzly

Added `ghost version` sub-command to the tool via the `root.go` file.

Currently set to `0.0.9` as per the latest release, this will need to be updated in the `root.go` file for the next release (currently on line 16).

When running `ghost version` the output will be:
```
$ ghost version
Ghost Version: 0.0.9
```

The output can be modified in the `fmt.Printf` command (line 24).

2023-06-13 16:39 UTC, Galzzly commented
Resolves #8

2023-06-13 16:46 UTC, Galzzly commented on cmd/root.go
> -
Removed these three lines for issue #9

2023-06-13 16:46 UTC, Galzzly commented
Added an extra commit to resolve #9

2023-06-14 02:51 UTC, savannahostrowski commented
Hey - thanks for the PR! Mind pulling #9 into a separate PR? The changes you made address that LGTM. 

For #8, I think that there's a slightly different variant that will make it so that I don't have to update the version string manually, e.g. via https://goreleaser.com/cookbooks/using-main.version/

2023-06-14 08:17 UTC, Galzzly commented
Hey, I've created PR #12 to deal with issue #9. I'm working on an update for this PR to make use of goreleaser. Will push that shortly.

2023-06-14 08:34 UTC, Galzzly commented
@savannahostrowski - I've made the update. 

`main.go` has `var version = "dev"` (can be updated to something more appropriate if wanted), and update `root.go` to have `var Version` which is set under `main.go` to whatever `version` is set to.

I performed a local release via `goreleaser` to confirm the `ghost version` output:
```
$ ./ghost version
Ghost Version: 0.0.9-SNAPSHOT-076329a
```

2023-06-15 02:04 UTC, savannahostrowski requested changes
One small suggestion for help menu consistency but other than that, this looks good to merge.

2023-06-15 02:04 UTC, savannahostrowski commented on cmd/root.go
> +		Use: "version",
```suggestion
		Use: "version",
		Short: "Prints the Ghost version"
```

2023-06-15 07:58 UTC, Galzzly commented
@savannahostrowski - accepted that suggestion, should be waiting for you to verify

2023-06-15 19:28 UTC, savannahostrowski approved these changes
Thanks for the update! LGTM!

2023-06-15 19:28 UTC, merged

2023-06-15 19:38 UTC, Galzzly commented
Absolutely no problem, happy to help. Give me a shout if you want a hand with anything else @savannahostrowski